version: '3.8'

services:
  app:
    build: .
    container_name: go_leaderboard_app
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=Jayesh
      - DB_PASSWORD=jayesh
      - DB_NAME=leaderboard
    ports:
      - "8080:8080"
